# Generated by Django 2.1.1 on 2018-09-14 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+2588[2-7][0-9]{7}$')])),
                ('active', models.BooleanField(default=True)),
                ('agent', models.BooleanField(default=False)),
                ('balance', models.PositiveIntegerField(default=0.0)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
