# Generated by Django 2.1.1 on 2018-09-14 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\+2588[2-7][0-9]{7}$')]),
        ),
    ]
