# Generated by Django 2.1.1 on 2018-09-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmola', '0002_auto_20180914_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='agent',
        ),
    ]
